spring:
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: create
    datasource:
      platform: h2
      url: jdbc:h2:tcp://:8082/~/tripsschema
      username: sa
      password:
      driverClassName: org.h2.Driver
